// <auto-generated/>
// This file was auto-generated by ULinkRPC.CodeGen. Do not edit.
#pragma warning disable

using System;
using Shared.Interfaces;
using System.Collections.Generic;
using ULinkRPC.Core;

namespace Rpc.Generated
{
    public static class PlayerCallbackBinder
    {
        private const int ServiceId = 1;

        private static readonly RpcPushMethod<List<PlayerPosition>> onMovePushMethod = new(ServiceId, 1);

        public static void Bind(IRpcClient client, IPlayerCallback receiver)
        {
            client.RegisterPushHandler(onMovePushMethod, (arg) =>
            {
                receiver.OnMove(arg);
            });

        }
    }
}
