// <auto-generated/>
// This file was auto-generated by ULinkRPC.CodeGen. Do not edit.
#pragma warning disable

using System;
using Shared.Interfaces;
using ULinkRPC.Core;

namespace Rpc.Generated
{
    public static class PlayerCallbackBinder
    {
        private const int ServiceId = 1;

        private static readonly RpcPushMethod<WorldState> onWorldStatePushMethod = new(ServiceId, 1);
        private static readonly RpcPushMethod<PlayerDead> onPlayerDeadPushMethod = new(ServiceId, 2);
        private static readonly RpcPushMethod<MatchEnd> onMatchEndPushMethod = new(ServiceId, 3);

        public static void Bind(IRpcClient client, IPlayerCallback receiver)
        {
            client.RegisterPushHandler(onWorldStatePushMethod, (arg) =>
            {
                receiver.OnWorldState(arg);
            });

            client.RegisterPushHandler(onPlayerDeadPushMethod, (arg) =>
            {
                receiver.OnPlayerDead(arg);
            });

            client.RegisterPushHandler(onMatchEndPushMethod, (arg) =>
            {
                receiver.OnMatchEnd(arg);
            });
        }
    }
}
