// <auto-generated/>
// This file was auto-generated by ULinkRPC.CodeGen. Do not edit.
#pragma warning disable

using System;
using System.Threading;
using System.Threading.Tasks;
using Shared.Interfaces;
using System.Collections.Generic;
using ULinkRPC.Core;

namespace Rpc.Generated
{
    public sealed class PlayerServiceClient : IPlayerService
    {
        private const int ServiceId = 1;
        private static readonly RpcMethod<LoginRequest, LoginReply> loginAsyncRpcMethod = new(ServiceId, 1);
        private static readonly RpcMethod<InputMessage, RpcVoid> submitInputRpcMethod = new(ServiceId, 2);
        private static readonly RpcMethod<RpcVoid, RpcVoid> logoutAsyncRpcMethod = new(ServiceId, 3);

        private readonly IRpcClient _client;

        public PlayerServiceClient(IRpcClient client) { _client = client; }

        public ValueTask<LoginReply> LoginAsync(LoginRequest req)
        {
            return LoginAsync(req, CancellationToken.None);
        }

        public ValueTask<LoginReply> LoginAsync(LoginRequest req, CancellationToken ct)
        {
            return _client.CallAsync(loginAsyncRpcMethod, req, ct);
        }

        public async ValueTask SubmitInput(InputMessage req)
        {
            await SubmitInput(req, CancellationToken.None);
        }

        public async ValueTask SubmitInput(InputMessage req, CancellationToken ct)
        {
            await _client.CallAsync(submitInputRpcMethod, req, ct);
        }

        public ValueTask LogoutAsync()
        {
            return LogoutAsync(CancellationToken.None);
        }

        public async ValueTask LogoutAsync(CancellationToken ct)
        {
            await _client.CallAsync(logoutAsyncRpcMethod, default, ct);
        }

    }

    public static class PlayerServiceClientExtensions
    {
        public static IPlayerService CreatePlayerService(this IRpcClient client)
        {
            if (client is null) throw new ArgumentNullException(nameof(client));
            return new PlayerServiceClient(client);
        }
    }
}


